---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(patchwork)
library(gridExtra)

```
```{r}
ChemWLs <- read_csv("allchem_with_medianWLs.csv")
HPUareas <- read_csv("HPUareas.csv")

ChemWL_areas <- ChemWLs %>% left_join(HPUareas, by = "HPU")


por <- 0.5
Cpor <- 0.4

ChemWL_areas <- ChemWL_areas %>% mutate(Porosity = por)
ChemWL_areas$Porosity[ChemWL_areas$HPU == "C horizon"] <- Cpor

TotalArea_ha <- sum(HPUareas$Area_ha[HPUareas$HPU != "C horizon"])

```


```{r}
# NO3HPU <- read_csv("NO3_and_medianWLs.csv")
# HPUareas <- read_csv("HPUareas.csv")
# 
# NO3HPU_areas <- NO3HPU %>% left_join(HPUareas, by = "HPU")
# 
# Porosity <- 0.5
# 
# TotalArea_ha <- sum(HPUareas$Area_ha)

#Volume of water for water level
# (Area * depth) * porosity
concentrations_areas <- ChemWL_areas %>% mutate(water_L = #calculate water volume in Liters
                                          (((median_ht_above_C_cm / 100) #Water table thickness in cm -> m
                                          * 10000)    # 1 ha in m2
                                          * Porosity) #multiply by porosity (set as 0.50) now m
                                          * 1000) #this yields m^3, convert to L by * 1000

concentrations_areas <- concentrations_areas %>% 
                mutate(conc_mgha = median_concentration * water_L) %>% #mg of NO3 as concentration(mg/L) * Liters of water
                mutate(conc_kgha = conc_mgha / 1000000) #convert mg to kg
```

```{r}
#mg/L 
#cm
#ha

#Volume of water for water level
# (Area * depth) * porosity
# NO3HPU_areas <- NO3HPU_areas %>% mutate(water_L = #calculate water volume in Liters
#                                           (((median_ht_above_C_cm / 100) #Water table thickness in cm -> m
#                                           * 10000)    # 1 ha in m2
#                                           * Porosity) #multiply by porosity (set as 0.50) now m
#                                           * 1000) #this yields m^3, convert to L by * 1000
# 
# NO3HPU_areas <- NO3HPU_areas %>% 
#                 mutate(NO3_mgha = NO3median_mgL * water_L) %>% #mg of NO3 as concentration(mg/L) * Liters of water
#                 mutate(NO3_kgha = NO3_mgha / 1000000) #convert mg to kg


```
Whole watershed value
 
```{r}

#finds whole watershed value on specific days where all HPUs have values

concentrations_areas_WS <- concentrations_areas %>%
  filter(HPU != "riparian") %>%
  group_by(name, Date) %>%
  summarize(conc_kgha = sum((conc_kgha*(Area_ha / TotalArea_ha)), na.rm = TRUE), numg = n())  %>%
  filter(numg == 6) %>%
  mutate(HPU = "Watershed")

concentrations_areas <- concentrations_areas %>% bind_rows(concentrations_areas_WS)


#find WS value based on median value for each HPU
medians_by_HPUs <- concentrations_areas %>% 
  filter(HPU %in% c("E", "Bhs", "typical", "Bh", "bimodal", "C horizon")) %>%
  group_by(name, HPU) %>%
  summarize(median_conc_kgha = median(conc_kgha, na.rm = TRUE), Area_ha = mean(Area_ha))
  
WS_wtd_mean_solum_C <- medians_by_HPUs %>%
  group_by(name) %>%
  summarize(mean_conc_kgha = sum((median_conc_kgha*(Area_ha / TotalArea_ha)), na.rm = TRUE), numg = n())

WS_wtd_mean_solum <- medians_by_HPUs %>%
  filter(HPU != "deep C") %>%
  group_by(name) %>%
  summarize(mean_conc_kgha = sum((median_conc_kgha*(Area_ha / TotalArea_ha)), na.rm = TRUE), numg = n())


solum_and_C_table <- WS_wtd_mean_solum_C %>%
  filter(name %in% c("NH4 mg N/L", "NO3 mg/L", "TDN mg/L")) 

solum_table <- WS_wtd_mean_solum %>%
  filter(name %in% c("NH4 mg N/L", "NO3 mg/L", "TDN mg/L")) 

solum_and_C_table
solum_table

```
 [1] "Al mg/L"    "Al-MP"      "Alm mg/L"   "Alo mg/L"   "Ba-MP"      "Ca mg/L"    "Ca-MP"      "Cl mg/L"    "DOC mg/L"  
[10] "F mg/L"     "Fe mg/L"    "Fe-MP"      "K mg/L"     "K-MP"       "Mg mg/L"    "Mg-MP"      "Mn mg/L"    "Mn-MP"     
[19] "Na mg/L"    "Na-MP"      "NH4 mg N/L" "NO3 mg/L"   "P-MP"       "Pb-MP"      "Rb-MP"      "Si mg/L"    "Si-MP"     
[28] "SO4 mg/L"   "Sr-MP"      "TDN mg/L"   "Zn-MP"  

TDN
```{r, fig.height= 6}
Analyte <- "TDN"
ForName <- paste(Analyte, "mg/L")
ForLabs <- paste(Analyte, "kg/ha")

sumplot <- concentrations_areas %>% filter(conc_kgha < 10) %>%
  filter(HPU %in% c("E", "Bhs", "typical", "Bh", "bimodal", "C horizon")) %>%
  filter(name == ForName) %>%
  mutate(dayofYear = yday(Date), monthday = mdy(paste(month(Date), day(Date), 2000))) %>%
  mutate(HPU = factor(HPU, levels = c("E","Bhs","typical", "bimodal", "Bh", "C horizon"))) %>%
  ggplot(aes(monthday, conc_kgha, color = HPU))+
  geom_point()+
  scale_x_date(date_labels = "%B")+
  xlab("month")+
  theme_classic()+
  theme(legend.position = "none")+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  ylab(ForLabs)+
  facet_grid(rows = "HPU")


sumtable <- concentrations_areas %>% 
  filter(HPU %in% c("E", "Bhs", "typical", "Bh", "bimodal", "C horizon")) %>%
  filter(name == ForName) %>%
  mutate(HPU = factor(HPU, levels = c("E","Bhs","typical", "bimodal", "Bh", "C horizon"))) %>%
  group_by(HPU) %>%
  summarize(median_kgha = median(conc_kgha, na.rm = TRUE)) %>%
  tableGrob()

plotNtable <- sumplot+sumtable 

plotNtable

concentrations_areas %>% filter(HPU == "Watershed")
```

NO3 mg N/L
```{r, fig.height= 6}
Analyte <- "NO3"
ForName <- paste(Analyte, "mg/L")
ForLabs <- paste(Analyte, "kg N/ha")

sumplot <- concentrations_areas %>% filter(conc_kgha < 10) %>%
  filter(HPU %in% c("E", "Bhs", "typical", "Bh", "bimodal", "C horizon")) %>%
  filter(name == ForName) %>%
  mutate(dayofYear = yday(Date), monthday = mdy(paste(month(Date), day(Date), 2000))) %>%
  mutate(HPU = factor(HPU, levels = c("E","Bhs","typical", "bimodal", "Bh", "C horizon"))) %>%
  ggplot(aes(monthday, conc_kgha * 0.2260, color = HPU))+
  geom_point()+
  scale_x_date(date_labels = "%B")+
  xlab("month")+
  theme_classic()+
  theme(legend.position = "none")+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  ylab(ForLabs)+
  facet_grid(rows = "HPU")


sumtable <- concentrations_areas %>% 
  filter(HPU %in% c("E", "Bhs", "typical", "Bh", "bimodal", "C horizon")) %>%
  filter(name == ForName) %>%
  mutate(HPU = factor(HPU, levels = c("E","Bhs","typical", "bimodal", "Bh", "C horizon"))) %>%
  group_by(HPU) %>%
  summarize(median_kgha = median(conc_kgha, na.rm = TRUE)) %>%
  tableGrob()

plotNtable <- sumplot+sumtable 

plotNtable

concentrations_areas %>% filter(HPU == "Watershed")
```
NH3
```{r, fig.height= 6}
Analyte <- "NH4"
ForName <- paste(Analyte, "mg N/L")
ForLabs <- paste(Analyte, "kg N/ha")

sumplot <- concentrations_areas %>% filter(conc_kgha < 10) %>%
  filter(HPU %in% c("E", "Bhs", "typical", "Bh", "bimodal", "C horizon")) %>%
  filter(name == ForName) %>%
  mutate(dayofYear = yday(Date), monthday = mdy(paste(month(Date), day(Date), 2000))) %>%
  mutate(HPU = factor(HPU, levels = c("E","Bhs","typical", "bimodal", "Bh", "C horizon"))) %>%
  ggplot(aes(monthday, conc_kgha, color = HPU))+
  geom_point()+
  scale_x_date(date_labels = "%B")+
  xlab("month")+
  theme_classic()+
  theme(legend.position = "none")+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  ylab(ForLabs)+
  facet_grid(rows = "HPU")


sumtable <- concentrations_areas %>% 
  filter(HPU %in% c("E", "Bhs", "typical", "Bh", "bimodal", "C horizon")) %>%
  filter(name == ForName) %>%
  mutate(HPU = factor(HPU, levels = c("E","Bhs","typical", "bimodal", "Bh", "C horizon"))) %>%
  group_by(HPU) %>%
  summarize(median_kgha = median(conc_kgha, na.rm = TRUE)) %>%
  tableGrob()

plotNtable <- sumplot+sumtable 

plotNtable

concentrations_areas %>% filter(HPU == "Watershed")
```

DON
```{r, fig.height= 6}


conc_area_wide <- concentrations_areas %>% pivot_wider(names_from = name, values_from = conc_kgha)
conc_area_wide <- conc_area_wide %>% mutate(DON = 'TDN mg/L' - 'NH4 mg N/L' - ('NO3 mg/L' * 0.2260))

Analyte <- "NH4"
ForName <- paste(Analyte, "mg N/L")
ForLabs <- paste(Analyte, "kg N/ha")

sumplot <- concentrations_areas %>% filter(conc_kgha < 10) %>%
  filter(HPU %in% c("E", "Bhs", "typical", "Bh", "bimodal", "C horizon")) %>%
  filter(name == ForName) %>%
  mutate(dayofYear = yday(Date), monthday = mdy(paste(month(Date), day(Date), 2000))) %>%
  mutate(HPU = factor(HPU, levels = c("E","Bhs","typical", "bimodal", "Bh", "C horizon"))) %>%
  ggplot(aes(monthday, conc_kgha, color = HPU))+
  geom_point()+
  scale_x_date(date_labels = "%B")+
  xlab("month")+
  theme_classic()+
  theme(legend.position = "none")+
  theme(panel.border = element_rect(colour = "black", fill=NA, size=1))+
  ylab(ForLabs)+
  facet_grid(rows = "HPU")


sumtable <- concentrations_areas %>% 
  filter(HPU %in% c("E", "Bhs", "typical", "Bh", "bimodal", "C horizon")) %>%
  filter(name == ForName) %>%
  mutate(HPU = factor(HPU, levels = c("E","Bhs","typical", "bimodal", "Bh", "C horizon"))) %>%
  group_by(HPU) %>%
  summarize(median_kgha = median(conc_kgha, na.rm = TRUE)) %>%
  tableGrob()

plotNtable <- sumplot+sumtable 

plotNtable

concentrations_areas %>% filter(HPU == "Watershed")
```

```{r}
HPUareas
```
```{r}
concentrations_areas %>% filter(name %in% c("TDN mg/L", "NH4 mg N/L", "NO3 mg/L")) %>%
  group_by(name) %>%
  summarize(count = length(median_concentration), firstDate = min(Date), lastDate = max(Date))
```

